var FADE_OUT_MILLISECONDS = 200;
var GLOBAL_TIMEOUT = 400;

var BACKSPACE_KEY = 8;
var TAB_KEY = 9;
var ENTER_KEY = 13;
var ESCAPE_KEY = 27;
var LEFT_KEY = 37;
var UP_KEY = 38;
var RIGHT_KEY = 39;
var DOWN_KEY = 40;

var MONTH_JANUARY = 1;
var MONTH_FEBRUARY = 2;
var MONTH_MARCH = 3;
var MONTH_APRIL = 4;
var MONTH_MAY = 5;
var MONTH_JUNE = 6;
var MONTH_JULY = 7;
var MONTH_AUGUST = 8;
var MONTH_SEPTEMBER = 9;
var MONTH_OCTOBER = 10;
var MONTH_NOVEMBER = 11;
var MONTH_DECEMBER = 12;
var MONTHS_IN_A_YEAR = 12;